name: wakelock_macos
description: >-2
  macOS platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.4.0
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock_macos

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  wakelock_platform_interface: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

dependency_overrides:
  # We override the platform dependencies of wakelock here because we use the example app for
  # integration testing and want to make sure that the CI always runs integration tests using the
  # current platform implementations.
  wakelock_platform_interface:
    path: ../wakelock_platform_interface

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WakelockMacosPlugin
        fileName: wakelock_macos.dart
